### Simple GET request
GET https://httpbin.org/get

### POST request with JSON
POST https://httpbin.org/post
Content-Type: application/json

{
  "test": "data",
  "action": "httprunner-test"
}

### Status check
GET https://httpbin.org/status/200